import type { Metadata } from "next";
import { Inter, Satisfy, Dancing_Script, Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./components/SideBar";
import AppShell from "./appShell";

 const inter = Inter({ 
  subsets: ['latin'],
  display:'swap',
  variable: '--font-inter'
});

 const satisfy = Satisfy({ 
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-satisfy'
});

 const dancing = Dancing_Script({ 
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-dancing'
});

 const roboto = Roboto({ 
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  display :'swap',
  variable: '--font-roboto'
});

 const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  variable:'--font-roboto_mono'
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto.variable} ${dancing.variable} ${satisfy.variable} ${roboto_mono.variable} ` }>
        <AppShell>
          {children}
        </AppShell>

      </body>
    </html>
  );
}
