import type { Metadata } from "next";
import { Inter, Satisfy, Dancing_Script, Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

export const inter = Inter({ 
  subsets: ['latin'],
  display:'swap',
  variable: '--font-inter'
});

export const satisfy = Satisfy({ 
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-satisfy'
});

export const dancing = Dancing_Script({ 
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-dancing'
});

export const roboto = Roboto({ 
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  display :'swap',
  variable: '--font-roboto'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto.variable} ${dancing.variable} ${satisfy.variable} bg-slightGreyBlue` }>
       <NavBar/>
        {children}
        </body>
    </html>
  );
}
